# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

env:
  global:
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true

install:
  - Rscript -e 'install.packages(c("remotes", "corrr", "pagedown", "GGally", "dslabs", "DT", "haven", "readr", "shiny", "xlsx"))'
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo apt install ./google-chrome-stable_current_amd64.deb
  - rm google-chrome-stable_current_amd64.deb
  - Rscript -e 'remotes::install_github("muschellij2/jhur")'

script:
  - make

# Build all branches, *including* gh-pages:
branches:
  only:
  - gh-pages
  - /.*/
