default:
  course_name_long: "Epi/Biostats Winter Institute - Introduction to R for Public Health Researchers
140.604.73"
  course_dates: "January 9-13 and 17-20, 2023"
  final_due_date: "January 25th at 11:59pm EST"
  grades_due: "January 27th"
  holiday: "In recognition of [Martin Luther King Jr. Day](https://en.wikipedia.org/wiki/Martin_Luther_King_Jr._Day), there will be no class on Monday January 16th, 2023."
  courseplus_web: "https://courseplus.jhu.edu/core/index.cfm/go/syl:syl.public.view/coid/17889/"
  courseplus_dropboxes: "https://courseplus.jhu.edu/core/index.cfm/go/db:main/coID/17889/"
  ta: "Padmashri Saravanan (psarava1 at jhu.edu)"
  instructors: "[Carrie Wright](https://carriewright11.github.io/) (cwrigh60 at jhu.edu), [Ava Hoffman](https://www.avahoffman.com/) (ava.hoffman at jhu.edu)"