default:
  course_name_long: "Epi/Biostats Summer Institute - Introduction to R for Public Health Researchers
140.604.79"
  course_dates: "June 12-16 and 20-23, 2023"
  final_due_date: "June 30th at 11:59pm EST"
  grades_due: "August ?"
  holiday: "In recognition of [Juneteenth](https://en.wikipedia.org/wiki/Juneteenth), there will be no class on Monday June 19th, 2023."
  courseplus_web: "https://courseplus.jhu.edu/core/index.cfm/go/syl:syl.public.view/coid/20767/"
  courseplus_dropboxes: "https://courseplus.jhu.edu/core/index.cfm/go/db:main/coID/20767/"
  courseplus_surveys: "https://courseplus.jhu.edu/core/index.cfm/go/survey2:admin.home/coID/20767/#!/"
  ta: "Rupshikha Sen (rsen6 at jhmi.edu)"
  instructors: "[Carrie Wright](https://carriewright11.github.io/) (cwrigh60 at jhu.edu), [Ava Hoffman](https://www.avahoffman.com/) (ava.hoffman at jhu.edu)"
  r_version: "(4.2.2 as of October 31, 2022)"
  r_dl_mac_m1: "https://cloud.r-project.org/bin/macosx/big-sur-arm64/base/R-4.2.2-arm64.pkg"
  r_dl_mac_intel: "https://cloud.r-project.org/bin/macosx/base/R-4.2.2.pkg"
  r_dl_windows: "https://cloud.r-project.org/bin/windows/base/R-4.2.2-win.exe"
  rstudio_dl_mac: "https://download1.rstudio.org/electron/macos/RStudio-2022.12.0-353.dmg"
  rstudio_dl_windows: "https://download1.rstudio.org/electron/windows/RStudio-2022.12.0-353.exe"

