default:
  course_dates: "January 9-13 and 17-20, 2023"
  final_due_date: "January 25th at 11:59pm EST"
  grades_due: "January 27th"
  holiday: "In recognition of [Martin Luther King Jr. Day](https://en.wikipedia.org/wiki/Martin_Luther_King_Jr._Day), there will be no class on Monday January 16th, 2023."
  courseplus_web: "[CoursePlus Website](https://courseplus.jhu.edu/core/index.cfm/go/syl:syl.public.view/coid/17889/)"