# Candace Savonen Apr 2021

name: Delete Preview

on:
  pull_request:
    types: [closed]

jobs:
  delete-preview:
    runs-on: ubuntu-latest
    steps:

      # This is because if a PR is closed before a render finishes it won't find it.
      - name: Sleep for 15 minutes
        run: sleep 900s
        shell: bash

      # Check out current repository
      - name: checkout
        uses: actions/checkout@v2.6.0
        with:
          fetch-depth: 0

      # Delete the branch!
      - name: Delete branch locally and remotely
        run: git push origin --delete preview-${{ github.event.pull_request.number }} || echo "No branch to delete"
